unstable_features = true
wrap_comments = true
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
edition = "2024"
style_edition = "2024"
hex_literal_case = "Lower"